### ISSUE TITLE
I tried to access with http://<containers_ip>:9090 but its showing 404 Error

### ISSUE THREAD

**Issue by IMTejesh95** [ritua2/gib#1]

**Comment by saumyashah7** [comment]
Hi,
Thanks for reaching out. It seems like wrong link have been pasted there. Please try accessing the webpage using https://URL_BASE:8443 . URL_BASE would be IP address of the web server. Here is the generalized version of the code for this project: https://github.com/ritua2/gib_express which is very easy to setup and customize.

**Comment by saumyashah7** [comment]
Setup can be done in very few steps using the instructions mentioned on https://github.com/ritua2/gib_express . Just need to update environment variables with few manual steps and the application will be up and running. Links to the installation videos for the setup are also available on that page which provides guidance in detail.

**Comment by saumyashah7** [comment]
Closing the issue since no further response.
